window_width: 1280
window_height: 720
window_frame: true
window_resizable: true
window_caption: "ArcadiaTales"
game_version: "0.1.2"
max_fps: 800
debug: false
tile_scale: 4
tile_image_size: 16
tile_size: 64
player_speed: 100
slime_speed: 50
chat:
  chat_open: false
  command_prefix: "/"
  max_lines_characters: 80
  max_input_characters: 100
  width: 600
  font_size: 16
  max_messages: 100
  max_shown_messages: 20
